///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxCostcoCI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxCostcoCIRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8a921617-86c0-47ef-a611-3de0decca28e")]
    public partial class RxCostcoCIRepository : RepoGenBaseFolder
    {
        static RxCostcoCIRepository instance = new RxCostcoCIRepository();
        RxCostcoCIRepositoryFolders.ReleaseNotesRanorexAutomatedSoftAppFolder _releasenotesranorexautomatedsoft;
        RxCostcoCIRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        RxCostcoCIRepositoryFolders.MainFormAppFolder _mainform;

        /// <summary>
        /// Gets the singleton class instance representing the RxCostcoCIRepository element repository.
        /// </summary>
        [RepositoryFolder("8a921617-86c0-47ef-a611-3de0decca28e")]
        public static RxCostcoCIRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxCostcoCIRepository() 
            : base("RxCostcoCIRepository", "/", null, 0, false, "8a921617-86c0-47ef-a611-3de0decca28e", ".\\RepositoryImages\\RxCostcoCIRepository8a921617.rximgres")
        {
            _releasenotesranorexautomatedsoft = new RxCostcoCIRepositoryFolders.ReleaseNotesRanorexAutomatedSoftAppFolder(this);
            _keypromptform = new RxCostcoCIRepositoryFolders.KeyPromptFormAppFolder(this);
            _mainform = new RxCostcoCIRepositoryFolders.MainFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8a921617-86c0-47ef-a611-3de0decca28e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ReleaseNotesRanorexAutomatedSoft folder.
        /// </summary>
        [RepositoryFolder("04256deb-47ae-4257-b8bf-8d4fdc81b2d6")]
        public virtual RxCostcoCIRepositoryFolders.ReleaseNotesRanorexAutomatedSoftAppFolder ReleaseNotesRanorexAutomatedSoft
        {
            get { return _releasenotesranorexautomatedsoft; }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("d42d0d63-6d73-41e9-bf08-cb71a5a409aa")]
        public virtual RxCostcoCIRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("ca422c22-82fc-44c9-bf7b-2e1632dde46b")]
        public virtual RxCostcoCIRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxCostcoCIRepositoryFolders
    {
        /// <summary>
        /// The ReleaseNotesRanorexAutomatedSoftAppFolder folder.
        /// </summary>
        [RepositoryFolder("04256deb-47ae-4257-b8bf-8d4fdc81b2d6")]
        public partial class ReleaseNotesRanorexAutomatedSoftAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ReleaseNotesRanorexAutomatedSoft  folder.
            /// </summary>
            public ReleaseNotesRanorexAutomatedSoftAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReleaseNotesRanorexAutomatedSoft", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "04256deb-47ae-4257-b8bf-8d4fdc81b2d6", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("04256deb-47ae-4257-b8bf-8d4fdc81b2d6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("04256deb-47ae-4257-b8bf-8d4fdc81b2d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("d42d0d63-6d73-41e9-bf08-cb71a5a409aa")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "d42d0d63-6d73-41e9-bf08-cb71a5a409aa", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "53242a46-d503-4992-95e2-e7e15e0cdad0");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "50588835-65b7-40c3-b426-cb56aee86df9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d42d0d63-6d73-41e9-bf08-cb71a5a409aa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d42d0d63-6d73-41e9-bf08-cb71a5a409aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("53242a46-d503-4992-95e2-e7e15e0cdad0")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("53242a46-d503-4992-95e2-e7e15e0cdad0")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("50588835-65b7-40c3-b426-cb56aee86df9")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("50588835-65b7-40c3-b426-cb56aee86df9")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca422c22-82fc-44c9-bf7b-2e1632dde46b")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "ca422c22-82fc-44c9-bf7b-2e1632dde46b", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "5f062f84-7aa9-4043-a148-1f298464bc51");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca422c22-82fc-44c9-bf7b-2e1632dde46b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca422c22-82fc-44c9-bf7b-2e1632dde46b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("5f062f84-7aa9-4043-a148-1f298464bc51")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("5f062f84-7aa9-4043-a148-1f298464bc51")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
